/**
 * Fixture-driven tests for the full action-mapping surface of `TxSignatureRequestDto`.
 *
 * Each fixture is a serialized `Transaction` generated by `scripts/generate-tx-fixtures.cjs`
 * using the exact same SDK builders that the wallet playground uses. The fixtures are
 * fed back through `Transaction.fromJSON()` — the same code path the wallet receives
 * when an external dApp sends a signing request — so we exercise real on-chain shapes
 * without needing a running wallet/playground.
 */
import { Transaction } from 'casper-js-sdk';
import * as fs from 'fs';
import * as path from 'path';
import { TxSignatureRequestDto, type TxSignatureRequestDtoProps } from './TxSignatureRequestDto';
import {
  isTxSignatureRequestAssociatedKeysAction,
  isTxSignatureRequestAuctionAction,
  isTxSignatureRequestCasperMarketAction,
  isTxSignatureRequestCep18Action,
  isTxSignatureRequestNativeCsprAction,
  isTxSignatureRequestNftAction,
  isTxSignatureRequestUnknownContractAction,
  isTxSignatureRequestWasmAction,
  isTxSignatureRequestWasmProxyAction,
} from '../../../utils';

const FIXTURES_DIR = path.resolve(__dirname, '..', '..', '..', '__fixtures__', 'transactions');

// Allow-listed fixture filenames. Every test path passes through this map, so we never
// build a filesystem path from an unconstrained string (silences static analyzers and
// genuinely prevents accidental traversal).
const FIXTURE_PATHS: Record<string, string> = {
  'cspr-native-transfer': `${FIXTURES_DIR}/cspr-native-transfer.json`,
  'auction-delegate': `${FIXTURES_DIR}/auction-delegate.json`,
  'auction-undelegate': `${FIXTURES_DIR}/auction-undelegate.json`,
  'auction-redelegate': `${FIXTURES_DIR}/auction-redelegate.json`,
  'nft-burn': `${FIXTURES_DIR}/nft-burn.json`,
  'cep18-transfer': `${FIXTURES_DIR}/cep18-transfer.json`,
  'cspr-market-list': `${FIXTURES_DIR}/cspr-market-list.json`,
  'associated-keys-set': `${FIXTURES_DIR}/associated-keys-set.json`,
  'unknown-contract': `${FIXTURES_DIR}/unknown-contract.json`,
  'wasm-session': `${FIXTURES_DIR}/wasm-session.json`,
  'wasm-proxy': `${FIXTURES_DIR}/wasm-proxy.json`,
  'legacy-cspr-transfer-deploy': `${FIXTURES_DIR}/legacy-cspr-transfer-deploy.json`,
  'legacy-auction-delegate-deploy': `${FIXTURES_DIR}/legacy-auction-delegate-deploy.json`,
  'legacy-cep18-transfer-deploy': `${FIXTURES_DIR}/legacy-cep18-transfer-deploy.json`,
};
const INDEX_PATH = `${FIXTURES_DIR}/index.json`;

const loadFixture = (name: keyof typeof FIXTURE_PATHS): Transaction => {
  const filePath = FIXTURE_PATHS[name];
  if (!filePath) {
    throw new Error(`Unknown fixture: ${name}`);
  }
  const raw = fs.readFileSync(filePath, 'utf8');
  return Transaction.fromJSON(JSON.parse(raw));
};

const indexFixture = JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8')) as {
  signingKey: string;
  fixtures: string[];
};

const SIGNING_KEY = indexFixture.signingKey;

const baseDto = (
  fixtureName: keyof typeof FIXTURE_PATHS,
  overrides: Partial<TxSignatureRequestDtoProps> = {},
) =>
  new TxSignatureRequestDto({
    tx: loadFixture(fixtureName),
    network: 'testnet',
    signingPublicKeyHex: SIGNING_KEY,
    csprFiatRate: '0.05',
    accountInfoMap: {},
    contractPackage: null,
    collectionContractPackage: null,
    rpcAccountInfo: null,
    isWasmProxyOnApi: false,
    ...overrides,
  });

describe('TxSignatureRequestDto — action mapping per fixture', () => {
  it('exposes top-level fields from the underlying Transaction', () => {
    const dto = baseDto('cspr-native-transfer');

    expect(dto.txHash).toMatch(/^[0-9a-f]+$/);
    expect(dto.id).toBe(dto.txHash);
    expect(dto.chainName).toBe('casper-test');
    expect(dto.expires).toMatch(/T.*Z$/);
    expect(dto.signingKey).toBe(SIGNING_KEY);
    expect(dto.senderKey).toBe(SIGNING_KEY);
    expect(dto.paymentAmount).toBe('100000000');
    expect(dto.formattedPaymentAmount).toBe('0.1');
    expect(dto.signaturesCollected).toEqual([]);
  });

  describe('Native transactions', () => {
    it('maps NativeTransfer → CSPR_NATIVE', () => {
      const dto = baseDto('cspr-native-transfer');
      expect(isTxSignatureRequestNativeCsprAction(dto.action)).toBe(true);
      if (isTxSignatureRequestNativeCsprAction(dto.action)) {
        expect(dto.action.amount).toBe('25000000000');
        expect(dto.action.recipientKey).toBe(
          '020329169b6c9e632fbeca5677fcad1bb48b87cd80500202911b933c16fa1d107e2e',
        );
      }
    });

    it('maps NativeDelegate → AUCTION (delegate)', () => {
      const dto = baseDto('auction-delegate');
      expect(isTxSignatureRequestAuctionAction(dto.action)).toBe(true);
      if (isTxSignatureRequestAuctionAction(dto.action)) {
        // Native v1 builders surface the entry-point name as TransactionEntryPointEnum
        // ("Delegate" / "Undelegate" / "Redelegate"); the wallet preserves the SDK's casing.
        expect(dto.action.entryPoint?.toLowerCase()).toBe('delegate');
        expect(dto.action.amount).toBe('2500000000');
      }
    });

    it('maps NativeUndelegate → AUCTION (undelegate)', () => {
      const dto = baseDto('auction-undelegate');
      expect(isTxSignatureRequestAuctionAction(dto.action)).toBe(true);
      if (isTxSignatureRequestAuctionAction(dto.action)) {
        expect(dto.action.entryPoint?.toLowerCase()).toBe('undelegate');
      }
    });

    it('maps NativeRedelegate → AUCTION (redelegate) with both validators', () => {
      const dto = baseDto('auction-redelegate');
      expect(isTxSignatureRequestAuctionAction(dto.action)).toBe(true);
      if (isTxSignatureRequestAuctionAction(dto.action)) {
        expect(dto.action.entryPoint?.toLowerCase()).toBe('redelegate');
      }
    });
  });

  describe('Contract calls', () => {
    it('maps NFT burn → NFT action', () => {
      const dto = baseDto('nft-burn', {
        // contract_type_id 4 = CEP47Nft → triggers isNftAction branch
        contractPackage: {
          id: 'nft-pkg',
          contractPackageHash: '6ca070c78d4eb468b4db4cbc5cadd815c35e15019a841c137372a88d7e247d1d',
          name: 'My NFTs',
          symbol: '',
          decimals: 0,
          iconUrl: null,
          latestVersionContractTypeId: 4,
        },
      });
      expect(isTxSignatureRequestNftAction(dto.action)).toBe(true);
      if (isTxSignatureRequestNftAction(dto.action)) {
        expect(dto.action.entryPoint).toBe('burn');
      }
    });

    it('maps CEP18 transfer → CEP18 action', () => {
      const dto = baseDto('cep18-transfer', {
        contractPackage: {
          id: 'cep18-pkg',
          contractPackageHash: '7fd113f60890c8ea77daf90880852f544b618c62315bcfd2dd93304c389fa19d',
          name: 'MockUSD',
          symbol: 'MUSD',
          decimals: 18,
          iconUrl: null,
          latestVersionContractTypeId: 2, // Cep18
        },
      });
      expect(isTxSignatureRequestCep18Action(dto.action)).toBe(true);
      if (isTxSignatureRequestCep18Action(dto.action)) {
        expect(dto.action.entryPoint).toBe('transfer');
        expect(dto.action.symbol).toBe('MUSD');
        expect(dto.action.decimals).toBe(18);
        // makeCep18TransferTransaction encodes the recipient as a Key/Account (account hash),
        // not the raw public key — the wallet preserves this faithfully.
        expect(dto.action.recipientKey).toMatch(/^[0-9a-f]{64}$/);
        expect(dto.action.recipientKeyType).toBe('accountHash');
      }
    });

    it('maps cspr-market list_token → CSPR_MARKET', () => {
      const dto = baseDto('cspr-market-list');
      expect(isTxSignatureRequestCasperMarketAction(dto.action)).toBe(true);
      if (isTxSignatureRequestCasperMarketAction(dto.action)) {
        expect(dto.action.entryPoint).toBe('list_token');
      }
    });

    it('maps associated keys set → ASSOCIATED_KEYS', () => {
      const dto = baseDto('associated-keys-set');
      expect(isTxSignatureRequestAssociatedKeysAction(dto.action)).toBe(true);
    });

    it('falls through to UNKNOWN for arbitrary contract calls without a matching package', () => {
      const dto = baseDto('unknown-contract');
      expect(isTxSignatureRequestUnknownContractAction(dto.action)).toBe(true);
    });
  });

  describe('Session (WASM) transactions', () => {
    it('maps a plain SessionBuilder tx → WASM action when isWasmProxyOnApi is false', () => {
      const dto = baseDto('wasm-session', { isWasmProxyOnApi: false });
      expect(isTxSignatureRequestWasmAction(dto.action)).toBe(true);
    });

    it('maps a wasm-proxy session tx → WASM_PROXY when isWasmProxyOnApi is true', () => {
      const dto = baseDto('wasm-proxy', { isWasmProxyOnApi: true });
      expect(isTxSignatureRequestWasmProxyAction(dto.action)).toBe(true);
    });

    it('falls back to WASM when isWasmProxyOnApi is false even for proxy-shaped args', () => {
      const dto = baseDto('wasm-proxy', { isWasmProxyOnApi: false });
      expect(isTxSignatureRequestWasmAction(dto.action)).toBe(true);
    });
  });

  describe('Legacy Deploys (Transaction.fromDeploy)', () => {
    it('maps legacy CSPR transfer Deploy → CSPR_NATIVE', () => {
      const dto = baseDto('legacy-cspr-transfer-deploy');
      expect(isTxSignatureRequestNativeCsprAction(dto.action)).toBe(true);
      if (isTxSignatureRequestNativeCsprAction(dto.action)) {
        expect(dto.action.recipientKey).toBe(
          '020329169b6c9e632fbeca5677fcad1bb48b87cd80500202911b933c16fa1d107e2e',
        );
      }
    });

    it('maps legacy auction delegate Deploy → AUCTION', () => {
      const dto = baseDto('legacy-auction-delegate-deploy');
      expect(isTxSignatureRequestAuctionAction(dto.action)).toBe(true);
      if (isTxSignatureRequestAuctionAction(dto.action)) {
        expect(dto.action.entryPoint).toBe('delegate');
      }
    });

    it('maps legacy CEP18 transfer Deploy → CEP18 when contract metadata is provided', () => {
      const dto = baseDto('legacy-cep18-transfer-deploy', {
        contractPackage: {
          id: 'cep18-pkg',
          contractPackageHash: '7fd113f60890c8ea77daf90880852f544b618c62315bcfd2dd93304c389fa19d',
          name: 'MockUSD',
          symbol: 'MUSD',
          decimals: 18,
          iconUrl: null,
          latestVersionContractTypeId: 2,
        },
      });
      expect(isTxSignatureRequestCep18Action(dto.action)).toBe(true);
    });
  });

  describe('rawJson preserves the source tx', () => {
    it.each(indexFixture.fixtures)('round-trips %s through Transaction.fromJSON()', name => {
      const dto = baseDto(name);
      expect(dto.rawJson).toContain('"chain_name"');
    });
  });
});
